version: 2.1
orbs:
  python: circleci/python@2.1.1

jobs:
  hello-job:
    docker:
      - image: cimg/node:17.2.0 # the primary container, where your job's commands are run
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout # check out the code in the project directory
      - run: echo "hello world" # run the `echo` command
  test-job:
    docker:
      - image: cimg/python:3.10.5 # the primary container, where your job's commands are run
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
          pip-dependency-file: requirements.txt
      - run:
         name: Test1
         command:
           python tests\test_pdf.py


workflows:
  my-workflow:
    jobs:
      - hello-job
      - test-job
